#    _         _        _   _                    
# \_|_)       | |      | | | |                   
#   |     __, | |   _  | | | |         _  _  _   
#  _|    /  | |/ \_|/  |/  |/  |   |  / |/ |/ |  
# (/\___/\_/|_/\_/ |__/|__/|__/ \_/|_/  |  |  |_/
                                               
# Labellum - Rose Madder Deep for Alacritty

[colors.primary] 
background = '#36262B' 
foreground = '#BBBBBB'

[colors.cursor]
text = '#1E1E2E'
cursor = '#BBBBBB'

[colors.normal]
black = '#303030'
red = '#cc6e7c'
green = '#b2bd8c'
yellow = '#daa286'
blue = '#84b0a7'
magenta = '#c37f9e'
cyan = '#98c1a1'
white = '#ABB2BF'

[colors.bright]
black = '#303030'
red = '#cc6e7c'
green = '#b2bd8c'
yellow = '#daa286'
blue = '#84b0a7'
magenta = '#c37f9e'
cyan = '#98c1a1'
white = '#ABB2BF'

[colors.dim]
black = '#303030'
red = '#cc6e7c'
green = '#b2bd8c'
yellow = '#daa286'
blue = '#84b0a7'
magenta = '#c37f9e'
cyan = '#98c1a1'
white = '#ABB2BF'

